### ISSUE TITLE
valid size values in ve_dma_post_wait()

### ISSUE THREAD

**Issue by noma** [veos-sxarr-NEC/libsysve#1]
The [documentation](https://veos-sxarr-nec.github.io/libsysve/group__vedma.html#ga6b9b4a101569a34e339506c9488951b9) of `ve_dma_post_wait`does not constrain the size parameter with respect to a minimal value, or to be a a multiple of 4 (like for the alignment of `dst`/`src`).

```c
int ve_dma_post_wait (uint64_t dst,
                      uint64_t src,
                      int size)  // "Transfer size less than 128MB"
```

It seems however, that one of the two constraints applies. In a code [HAM](https://github.com/noma/ham), my transfers of 9 and 10 byte-sized payloads wouldn't work as expected. In a series of transfers, the values wouldn't appear on the host when they were expected, but later, seemingly triggered by successive calls to `ve_dma_post_wait()`.

Can you please specify what the exact constraints are, and update the documentation as needed? Thanks.

**Comment by veos-sxarr** [comment]
Hello.

The size must be a multiple of 4, because the lower 2 bits of the transfer length in DMA descriptor table is hardwired to zero.
We will update the document to describe this constraint.

**Comment by veos-sxarr** [comment]
We have updated the document.
Please refer to the latest document.
https://veos-sxarr-nec.github.io/libsysve/group__vedma.html
